### ISSUE TITLE
[BUG] Cb Defense Device objects give incorrect timestamp for datetime.datetime attributes

### ISSUE THREAD

**Issue by Ciznit** [carbonblack/cbapi-python#214] opened 2020-01-28 18:37 UTC
**I am seeing this behaviour on: (please complete the following information):**
 - OS: MacOS 10.15.2
 - Carbon Black Product: CB Defense
 - Python Version: 3.7.3

**Describe the bug**
cbapi.psc.defense.Device have some attributes (lastContact, lastShutdownTime, etc.) that are timestamps. When these attributes are accessed they get converted to datetime.datetime objects. However, instead of being the correct datetime, they always end up evaluating to '1970-01-01 00:00:00'.

I believe this is related to the fact that Cb Defense gives timestamps in milliseconds, but the datetime library works with timestamps in seconds.

**Steps to Reproduce**
The following code reproduces the issue and highlights various behaviors handling timestamps:

> \# for the sake of this example, assume the vale of device.lastContact is 1580235662515
>
>import cbapi
>import datetime
>
>def_api = cbapi.CbDefenseAPI()
>device = def_api.select(cbapi.psc.defense.Device).first()
>
>\# timestamp is correct when printing object
>print(device) \# prints all attributes, including 'lastContact: 1580235662515'
>
>\# accessing timestamp attribute give incorrect datetime object
>print(device.lastContact) \# prints '1970-01-01 00:00:00'
>
>\# directly accessing timestamp gives correct timestamps
>print(device.__dict__['_info']['lastContact']) \# prints '1580235662515'
>
>\# directly accessing timestamp and converting from ms to seconds,
>\# then converting to timestamp give correct datetime
>print(datetime.datetime.fromtimestamp(device.__dict__['_info']['lastContact']/1000)) \# prints 2020-01-28 12:21:02.515000
>
>\# not converting to seconds throws an error
>print(datetime.datetime.fromtimestamp(device.__dict__['_info']['lastContact']))
>\# throws the following error:
>\# Traceback (most recent call last):
>\#   File "cbapi_bug.py", line 22, in <module>
>\#     print(datetime.datetime.fromtimestamp(device.__dict__['_info']['lastContact']))
>\# ValueError: year 52045 is out of range

**Expected behavior**
Access timestamp attributes from Cb Defense Device objects returns the correct datetime object.

**Actual behavior**
Access timestamp attributes from Cb Defense Device objects always returns a datetime object with the value '1970-01-01 00:00:00'

**Comment by valoulou** [comment] 2020-03-19 22:00
Hi @Ciznit,

I have the same issue and I found where the problem is. 

If you look inside 'src/cbapi/models.py' line 147 you will see : 

`if type(d) is float or isinstance(type(d), integer_types):`

The second condition is always wrong. I think the fix is : 

`if type(d) is float or type(d) is int:`

It works for me, I'm going to make a pull request.

Thanks!

**Comment by snowmirage** [comment] 2020-05-14 19:52
Any ETA on this by chance?  I just ran into the same problem with 1.6.2 looks like its been kicking around a while.

**Comment by valoulou** [comment] 2020-05-14 19:57
I haven't done a new test and I haven't seen any news about it either ... Have you tried my solution? Maybe a quickwin while waiting for a fix.

**Comment by jleaniz** [comment] 2020-07-03 14:19
Yeah, this is bad.

**Comment by avanbrunt-cb** [comment] 2020-07-10 21:52
Fix pushed to master to correct this bug https://github.com/carbonblack/cbapi-python/commit/9ab1930ff0898b36514ad0712b7e337bed0358bb

**Comment by avanbrunt-cb** [comment] 2020-07-15 17:37
This will be released with 1.7.0

**Closed by avanbrunt-cb** 2020-07-15 17:37 UTC
Labels: bug
